# Generated by Django 4.2.7 on 2023-11-26 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место для привычки')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала привычки')),
                ('action', models.CharField(max_length=100, verbose_name='Действие привычки')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='DAILY', verbose_name='Частота выполнения')),
                ('award', models.CharField(blank=True, max_length=100, null=True, verbose_name='Награда за привычку')),
                ('duration', models.IntegerField(verbose_name='Продолжительность привычки')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная привычка')),
                ('link_pleasant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Ссылка на приятную привычку')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
